language: ruby
dist: bionic
rvm:
  - 2.5.5

sudo: false

env:
  STREAM_API_KEY=q3k9n9kqk3fb
  STREAM_API_SECRET=vkw87x3p323z6ma75n8dvnse98jrr9gkauf2zfjnzbgjpmm54ssnbync4yhhzugc
  CC_TEST_REPORTER_ID=5e2172ea5a30b07e172058a3b33dfe08c6354699808e8f3010acc32b1ef41395
  BUNDLE_GITHUB__HTTPS=true
  LOG_LEVEL=warn

cache:
  directories:
    - vendor/bundle

before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.2/elasticsearch-2.4.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.2.deb && sudo systemctl restart elasticsearch
  - systemctl status elasticsearch
  - sudo cat /etc/elasticsearch/elasticsearch.yml
  - sudo lsof -i
  - sleep 30

install:
  - bundle install --deployment --jobs=3 --retry=3
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter


before_script:
  - bundle exec rake db:create db:schema:load
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Postgres v9.4 and ElasticSearch 2.x
services:
  - elasticsearch
  - redis-server
  - mongodb
addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch
  postgresql: 9.4

notifications:
  email: false
  slack:
    secure: kWuOR9YLV9FRX8wkr/pIvrdLzEcmUG7WYnqkS13T26+o+XyVa3E1ESqmOgCYMU9D0+5jjweRSNRVk7YCKcAwgcMFvwbbMgxVmmPeAOzVant9B1kv8HzdXE7Gd5eipItSxEELYa8ufhVOu5nY/vbCgyr/soPIKbRcDqf3QEXj0a7iWt57bPaRwN/13y1DOy0E1DJuVu4a4oVfsCerVWGYeJafFg7xVVZnvKLS0pqF5zrYuUzvO2hrnGdKz4CvRZym20XDAvhfmG4udcgld2mrxcDF6hJpM3bGDew91/ns+hEyLev44G76Z8XsI/em9d0FQfe27zdzIfaTOWUKY72fbgrJX+YU+HjS5MHRzgZE79nS8b+91VM1EazGPeHsy93ihdXoqkQ0vHHZgxzpjbTBXmLUgRCk3Vb5tc5wspEWTjOi2X7UAUQG3n9iiy7vMfu+/4HUgG8kL97MjmZaNSYTcfv0UDvU8nssRyD/rqMD/Vy6ZXhU/O0Hn47A6a2sgcXXw4neJwwDAC4hKBY89WeCYU6YQU+CnKuc7kHcDmjHBvbV+gXRBQitC5ew3ZZhloDBJYkD52MMOrsgxj+gt6JypKXdX0kXNnXt2HfsbazX/EJMSEL4XMLsmDWzhociFBTLz7QhdznBUg7p6X5kwyM1L0FihTsc+s3Bag/h/CNk5Ag=
