default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: kitsu_development

test:
  <<: *default
  database: kitsu_test

production:
  <<: *default
  database: kitsu_production
