default: &default
  adapter: postgresql
  encoding: unicode
<% if $0.include?('sidekiq') %>
  reaping_frequency: 10
  checkout_timeout: 5
  pool: 45 # Concurrency from sidekiq.yml
  variables:
    lock_timeout: 20s
<% elsif $0.include?('rake') %>
  connect_timeout: 5
  connect_timeout: 5
  variables:
    lock_timeout: 10s
<% else %>
  pool: <%= (ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40) * 1.2 %>
  connect_timeout: 5
  checkout_timeout: 2
  reaping_frequency: 30
  variables:
    lock_timeout: 6s
    statement_timeout: 15s
<% end %>

development:
  <<: *default
  database: kitsu_development

test:
  <<: *default
  database: kitsu_test

production:
  <<: *default
  database: kitsu_production
