default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40 %>
  connect_timeout: 5
  checkout_timeout: 2
  variables:
    lock_timeout: 6s
    statement_timeout: 15s

development:
  <<: *default
  database: kitsu_development

test:
  <<: *default
  database: kitsu_test

production:
  <<: *default
  database: kitsu_production
