---
:concurrency: 6
production:
  :concurrency: 40
:queues:
  - [default, 3]
  - [mailers, 2]
  - [paperclip, 2]
  - [notifications, 3]
  - [chewy, 1]
:schedule:
  CounterCacheResetWorker:
    every: 12h
  AverageRatingUpdateWorker:
    every: 6h
  RankingUpdateWorker:
    every: 12h
  LibraryEntryLogRemovalWorker:
    every: 12h
  UploadRemovalWorker:
    every: 12h
  HuluMappingWorker:
    every: 24h
